import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import SessionWrapper from "./components/SessionWrapper";
import { getSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  session,
  children,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  console.log("session", session);
  session = getSession();
  console.log("session", session);

  return (
    <SessionWrapper session={session}>
      <html lang="en">
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
